### PR TITLE
Update wikibase-codesniffer to v1.2.0

### PR DESCRIPTION
**Pull request by itamargiv**
In addition, changed line length restriction to 120 (as this is the PSR-12 recommendation and there were plenty of cs warnings about violations to the 101 line length rule).

Bug: [T264836](https://phabricator.wikimedia.org/T264836)

### CODE REVIEW

**Comment by micgro42** [comment]
Is the line length check actually enforced in this repository's CI? Because for Wikibase it isn't.

**Comment by itamargiv** [comment]
Great question, where can I check that?

**Comment by itamargiv** [comment]
@micgro42 To answer your question, yes it seems like it was affecting Travis, as it caused my other PR #20 to fail (had to change the base to this branch to make CI pass)

**Review by lucaswerkmeister — APPROVED** [review]

**Comment by micgro42** [comment]
Looks good to me, just a typo in the commit message of the line length commit.

**Comment by itamargiv** [comment]
Does this mean I can merge this?

**Comment by lucaswerkmeister** [comment]
Either merge it as-is or force-push a new version with a fixed commit message, I guess. I’d be okay with merging. (It should be a proper merge or rebase, not a squash, so that the LIBXML_NOBLANKS part stays separate.)

**Comment by micgro42** [comment]
> Does this mean I can merge this?

I wouldn't mind seeing this fixed, otherwise I wouldn't have mentioned it but would have merged this PR directly.

**Comment by micgro42** [comment]
> Either merge it as-is or force-push a new version with a fixed commit message, I guess. I’d be okay with merging. (It should be a proper merge or rebase, not a squash, so that the LIBXML_NOBLANKS part stays separate.)

Preferably "Rebase and Merge". Maybe this will even get rid of that merge commit that is currently part of this PR?

**Comment by itamargiv** [comment]
@micgro42 done

**Pull request merged**
